name: Azure Login Test

on:
  push:
    branches:
      - master

jobs:
  login-test:
    runs-on: ubuntu-latest

    env:
      AZURE_HTTP_USER_AGENT: github-actions-sp-login

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Azure Login using SP Secret
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: false

      - name: Force clear any federated env
        run: |
          unset ACTIONS_ID_TOKEN_REQUEST_URL
          unset ACTIONS_ID_TOKEN_REQUEST_TOKEN
          unset ARM_USE_OIDC
          unset ARM_OIDC_TOKEN

      - name: Verify Login
        run: az account show
