name: Build and Deploy to AKS

on:
  push:
    branches:
      - master
  
env:
  IMAGE_NAME: coreapi

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout source code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Login to Azure using Service Principal
      - name: Azure Login
        uses: azure/login@v2
        with:
         auth-type: SERVICE_PRINCIPAL
         client-id: 9c1feba3-5916-49e7-85f8-ecf5d6ed4441
         tenant-id: 139e417b-5236-4c6b-8570-2c8568bb1be4
         subscription-id: ad610489-8296-47cc-8938-28d5f67f7cc9
         client-secret: 4Pz8Q~sz1eryvZYCarkmCzcTE0xg_.fBs1MypbLV

      # 3. Login to Azure Container Registry
      - name: Login to ACR
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      # 4. Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

      # 5. Push Docker Image to ACR
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      # 6. Set AKS Cluster Context
      - name: Set AKS Context
        run: |
          az aks get-credentials \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --name ${{ secrets.AKS_CLUSTER_NAME }} \
            --overwrite-existing

      # 7. Deploy latest image to AKS
      - name: Deploy to AKS
        run: |
          kubectl set image deployment/myapp myapp=${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          kubectl rollout status deployment/myapp
